package dataobjects;

import annotations.ValidatingFactoryCall;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import valuetypes.Email;
import valuetypes.Password;
import valuetypes.Username;

@ValidatingFactoryCall
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public class CreateUserProfileRequestWithAnnotation {
    public final Email email;
    public final Password password;
    public final Username username;

    /*
    this will compile when the annotation processing step actually works.

    private static void validate(final FactoryCall call) {
        on(call).requireAll();
    }*/

    public static CreateUserProfileRequestWithAnnotation createUserProfileRequest(Email e, Password p, Username u) {
        throw new RuntimeException("this method is to be generated by lombok through @ValidatingFactoryCall");
    }
}
